#ifndef __LIVE_MASK_H__
#define __LIVE_MASK_H__

#include "MakeFrame.h"
#include <opencv2/videoio.hpp>
#include <opencv2/opencv.hpp>
#include <thread>

using namespace cv;

#define THRESHOLD_MAX 255
#define THRESHOLD_MIN 0
#define THRESHOLD_STEP 1

#define BL_KERNEL_MIN 1
#define BL_KERNEL_MAX 15
#define BL_KERNEL_STEP 2

/*
int liveMask(cv::Mat control, cv::VideoCapture interaction, cv::VideoCapture fill, int threshold);

Function to make and display a live feed from "fill" through a mask generated by the difference
between a frame from "interaction" and the "control" image
*/
int liveMask( cv::VideoCapture interaction,
              cv::VideoCapture fill,
              cv::Size desiredres,
              int threshold,
              void (*reorient)(cv::Mat),
              cv::VideoWriter* video
            );

#endif

